import { loadFont } from "@remotion/google-fonts/Roboto";

// Load Roboto with the weights we use for display + captions.
const { fontFamily } = loadFont("normal", {
  weights: ["400", "500", "700", "900"],
});

export const FONT_FAMILY = fontFamily;

// Official Altitude palette (matches the presentation for continuity),
// plus a couple of tuned tints for higher text contrast on navy.
export const COLORS = {
  navy: "#00203D",
  navyDeep: "#001428",
  blue: "#0071CE",
  blueBright: "#5EB2EA", // brighter kicker/accent for contrast on navy
  summit: "#CEE5F6",
  trailhead: "#F4F2ED",
  ink: "#FFFFFF",
  basecamp: "#2E3B40",
} as const;

export const FPS = 30;

// Transition overlap between top-level scenes.
export const TRANSITION = 15;

// Frames a card is on top inside the asset deck (dwell + fly-off). The last
// card does not fly — the deck slides into the result scene instead.
// Cropped variants (generated by crop.mjs) — the gray CleanShot matte trimmed
// off so each app window fills the panel edge-to-edge. All share ~1.156 ratio.
export const DECK_CARDS = [
  { key: "gather", src: "chat-compile-crop.png", dur: 210 },
  { key: "verify", src: "doc-storyboard-crop.png", dur: 210 },
  { key: "storyboard", src: "chat-revision-crop.png", dur: 210 },
  { key: "style", src: "gpt-images-crop.png", dur: 180 },
  { key: "build-a", src: "doc-buildspec-crop.png", dur: 130 },
  { key: "build-b", src: "claude-design-crop.png", dur: 130 },
] as const;

// Aspect ratio of the cropped app-window content.
export const CARD_ASPECT = 1.156;

export const DECK_DURATION = DECK_CARDS.reduce((a, c) => a + c.dur, 0); // 1070

// Frames the top card takes to fly off (and the next to rise to front).
export const FLY = 24;

// Top-level scene durations (before transition overlap).
export const SCENE = {
  hook: 120,
  recipe: 150,
  deck: DECK_DURATION,
  result: 420,
  close: 240,
} as const;

const RAW_TOTAL = Object.values(SCENE).reduce((a, b) => a + b, 0);
const TRANSITION_COUNT = Object.keys(SCENE).length - 1; // 4

// Rendered duration = sum(scenes) - sum(transitions).
export const TOTAL_DURATION = RAW_TOTAL - TRANSITION_COUNT * TRANSITION; // 1940
